"""Build a human-readable report.md from a host's raw scan outputs."""
from __future__ import annotations

import glob
import json
import os
import re


def _loadl(path):
    rows = []
    if os.path.isfile(path):
        for ln in open(path, encoding="utf-8-sig", errors="replace"):
            ln = ln.strip().lstrip("﻿")
            if ln:
                try:
                    rows.append(json.loads(ln))
                except ValueError:
                    pass
    return rows


def _read(path):
    return open(path, encoding="utf-8-sig", errors="replace").read() if os.path.isfile(path) else ""


def build_report(target, out_dir):
    L = []
    w = L.append

    def p(*parts):
        return os.path.join(out_dir, *parts)

    w(f"# easm-recon report — {target}")
    w(f"_output: {out_dir}_")
    w("")

    dns = _loadl(p("dns.jsonl"))
    hx = _loadl(p("httpx.jsonl"))
    tls = _loadl(p("tlsx.jsonl"))

    # Reachability status
    if not (dns or hx or tls):
        w("## Status")
        w("- **Host did not resolve / unreachable** — no DNS/HTTP/TLS data.")
        w("  (Invalid domain, offline, or internal-only.)")
        w("")
    elif not (hx or tls):
        w("## Status")
        w("- **Resolves in DNS but did not answer over HTTP/HTTPS** (timeout / closed / filtered).")
        w("  WAF/HTTP/TLS sections are empty because the host is not live — not a tool error.")
        w("")

    if dns:
        w("## DNS")
        for r in dns:
            a = ", ".join(r.get("a", []) or [])
            aaaa = ", ".join(r.get("aaaa", []) or [])
            cname = ", ".join(r.get("cname", []) or [])
            ns = ", ".join(r.get("ns", []) or [])
            line = f"- **{r.get('host','')}** A: {a or '-'}"
            if aaaa:
                line += f" | AAAA: {aaaa}"
            if cname:
                line += f" | CNAME: {cname}"
            if ns:
                line += f" | NS: {ns}"
            w(line)
        w("")

    cdn = _loadl(p("cdncheck.jsonl"))
    if cdn:
        w("## CDN / WAF / cloud (cdncheck)")
        for r in cdn:
            name = r.get("cdn_name") or r.get("waf_name") or r.get("cloud_name") or "-"
            kind = "WAF" if r.get("waf") else ("CDN" if r.get("cdn") else ("Cloud" if r.get("cloud") else "?"))
            w(f"- {r.get('input','')} -> {kind}: {name}")
        w("")

    if hx:
        w("## HTTP probe (httpx)")
        for r in hx:
            tech = ", ".join(r.get("tech", []) or [])
            w(f"- **{r.get('url','')}** [{r.get('status_code','')}] {r.get('title','') or ''}")
            det = []
            if r.get("webserver"):
                det.append(f"server={r['webserver']}")
            if r.get("cdn_name"):
                det.append(f"cdn={r['cdn_name']}")
            if r.get("location"):
                det.append(f"-> {r['location']}")
            if tech:
                det.append(f"tech: {tech}")
            if det:
                w("    - " + " | ".join(det))
        w("")

    _waf_section(w, out_dir, bool(hx or tls))
    _tls_section(w, tls)
    _ports_section(w, out_dir)
    _nuclei_section(w, out_dir)
    _subs_section(w, out_dir)

    w("---")
    w("_Generated by easm-recon. Active steps (ports/nuclei) must only be run against authorized targets._")
    open(p("report.md"), "w", encoding="utf-8").write("\n".join(L))


def _waf_section(w, out_dir, reachable):
    lines = []
    empty = False
    for wf in sorted(glob.glob(os.path.join(out_dir, "wafw00f*.json"))):
        try:
            data = json.load(open(wf, encoding="utf-8-sig", errors="replace"))
        except ValueError:
            empty = True
            continue
        if isinstance(data, dict):
            data = [data]
        det = [d for d in data if d.get("detected")]
        if det:
            for d in det:
                lines.append(f"**{d.get('firewall','?')}** ({d.get('manufacturer','')}) — {d.get('url','')} [wafw00f]")
        elif data:
            lines.append(f"wafw00f: none detected — {data[0].get('url','')}")
        else:
            empty = True
    wd = _read(os.path.join(out_dir, "waf_detect.txt"))
    if not lines and wd:
        m = re.search(r">>> VERDICT:.*", wd)
        if m:
            lines.append(m.group(0).replace(">>> VERDICT:", "").strip())
    if not lines and empty and reachable:
        lines.append("wafw00f: no result (host may not have answered over HTTP/HTTPS)")
    if lines:
        w("## WAF detection")
        for x in lines:
            w("- " + x)
        w("")


def _tls_section(w, tls):
    if not tls:
        return
    w("## TLS / certificate (tlsx)")
    for r in tls:
        san = ", ".join((r.get("subject_an") or [])[:8])
        issuer = r.get("issuer_org")
        issuer = issuer[0] if isinstance(issuer, list) and issuer else (issuer or "")
        w(f"- {r.get('host','')}:{r.get('port','')} — {r.get('tls_version','')} | CN={r.get('subject_cn','')} | issuer={issuer}")
        if san:
            w(f"    - SAN: {san}")
        flags = [k for k in ("expired", "self_signed", "mismatched") if r.get(k)]
        if flags:
            w(f"    - WARNING: {', '.join(flags)}")
    w("")


def _ports_section(w, out_dir):
    nm = _read(os.path.join(out_dir, "nmap.txt"))
    if nm:
        w("## nmap")
        w("```")
        w("\n".join(nm.splitlines()[:40]))
        w("```")
        w("")
        return
    ps = _read(os.path.join(out_dir, "portscan.txt"))
    if ps.strip():
        m = re.search(r"OPEN PORTS:\s*(.*)", ps)
        w("## Open ports (TCP connect scan)")
        w("- " + (m.group(1).strip() if m else "-"))
        w("")
        return
    na = _loadl(os.path.join(out_dir, "naabu.jsonl"))
    if na:
        w("## Open ports (naabu)")
        w("- " + ",".join(str(r.get("port")) for r in na if r.get("port")))
        w("")


def _nuclei_section(w, out_dir):
    jsonl = os.path.join(out_dir, "nuclei.jsonl")
    ran = os.path.isfile(jsonl) or os.path.isfile(os.path.join(out_dir, "nuclei_run.log"))
    if not ran:
        return
    nu = _loadl(jsonl)
    status_txt = _read(os.path.join(out_dir, "nuclei_status.txt"))
    incomplete = "TRUNCATED" in status_txt
    errored = status_txt.startswith("ERROR")
    w("## Vulnerabilities / exposure (nuclei)")
    if errored and not nu:
        w("- ⚠️ **nuclei did NOT run** (launch blocked by antivirus / security policy, "
          "or unavailable — see nuclei_run.log).")
        w("- This is **not** a clean result: no vulnerability data was collected.")
        w("")
        return
    if incomplete:
        w("- ⚠️ **nuclei INCOMPLETE** (stopped by timeout — PARTIAL result; real finding count may be higher).")
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4, "unknown": 5}
    if nu:
        nu.sort(key=lambda r: order.get((r.get("info", {}) or {}).get("severity", "unknown"), 9))
        w(f"- {'Up to cutoff' if incomplete else 'Total'} **{len(nu)} findings**:")
        for r in nu:
            info = r.get("info", {}) or {}
            w(f"  - [{info.get('severity','?').upper()}] {info.get('name', r.get('template-id',''))} — {r.get('matched-at', r.get('host',''))}")
    elif not incomplete:
        w("- Scan complete, **0 findings** (severity low-critical). Normal for static/hardened targets.")
    else:
        w("- (no findings written before cutoff)")
    w("")


def _subs_section(w, out_dir):
    subs = _read(os.path.join(out_dir, "subdomains.txt"))
    if not subs.strip():
        return
    items = [x.strip().lstrip("﻿") for x in subs.splitlines() if x.strip()]
    w(f"## Subdomains ({len(items)})")
    for s in items[:40]:
        w("- " + s)
    if len(items) > 40:
        w(f"- … (+{len(items) - 40} more; see subdomains.txt)")
    w("")
